language: ruby

services:
  - mongodb

matrix:
  include:
    - rvm: 2.4.1
      env:
        - MONGOID_VERSION=7
    - rvm: 2.4.1
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=5
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=HEAD
    - rvm: 2.3.0
      before_script:
        - bundle exec danger
